shell ="/bin/bash"

live_config_reload = true
ipc_socket = true

[window]
padding = {x = 2, y = 2}
dynamic_padding = true
opacity = 0.8
dynamic_title = true
decorations_theme_variant = "Dark"
resize_increments = true

[scrolling]
history = 100000
multiplier = 3

[font]
normal = {family = "Anonymous Pro", style = "Regular"}
bold = {family = "Anonymous Pro", style = "Bold"}
italic = {family = "Anonymous Pro", style = "Italic"}
size = 10
offset = {x = 1, y = 5}

[colors]
primary = {background = "0x1E1D2F", foreground = "0xD9E0EE"}

cursor = {text = "0x1E1D2F", cursor = "0xF5E0DC"}

# Normal colors
normal = {black = "0x6E6C7E", red = "0xF28FAD",green = "0xABE9B3", yellow = "0xFAE3B0", blue = "0x96CDFB", magenta = "0xF5C2E7",cyan = "0x89DCEB", white = "0xD9E0EE"}

# Bright colors
bright = {black = "0x988BA2", red = "0xF28FAD",green = "0xABE9B3", yellow = "0xFAE3B0", blue = "0x96CDFB", magenta = "0xF5C2E7",cyan = "0x89DCEB", white = "0xD9E0EE"}

indexed_colors = [{index = 16, color = "0xF8BD96"}, {index = 17, color = "0xF5E0DC"}]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[bell]
animation = "EaseOutExpo"
duration = 1 

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[mouse]
bindings = [{mouse = "Middle", mods = "Control", action = "Copy"}]
hide_when_typing = true

[cursor]
style = {shape = "Underline",blinking = "Always"}

[terminal]
osc52 = "CopyPaste"

