#! /bin/bash
sxhkd & 
~/.config/polybar/launch.sh &
picom &

bspc monitor -d term web web2 fs fun music sett none none none 

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer       true


#bspc config border_radius               2



bspc rule -a nvim desktop='^8' state=floating follow=on
bspc rule -a brave-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a dolphin desktop='^4' follow=on

bspc config normal_border_color               "#bcad2b"
bspc config active_border_color               "#005f3a"
bspc config focused_border_color	      "#c2faff"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#ffa18c"

feh --bg-fill --randomize ~/Pictures/Wallpapers
