#! /bin/bash
sxhkd & 
~/.config/polybar/launch.sh &
#picom &

bspc monitor -d term none web none web2 fs fun music sett none 

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_follows_pointer	true

bspc rule -a code-oss desktop='^2' follow=on
bspc rule -a firefox desktop='^3' follow=on 
bspc rule -a Picture-in-Picture state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop='^6' follow=on

bspc config normal_border_color               "#bcad2b"
bspc config active_border_color               "#005f3a"
bspc config focused_border_color	      "#c2faff"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#ffa18c"
dunst -config "$HOME"/.config/dunst/dunstrc &

# randomizing the background to $HOME/Pictures/Wallpapers
feh --bg-fill --randomize ~/Pictures/Wallpapers
